[DB]
  Type = "mysql"
  Path = "./"
  Addr = "localhost"
  Port = "3306"
  User = "user"
  Password = "1234"
  Name = "db_name"

[Gen]
  SchemaPath = "../output/schema.hcl"
  ConfigPath = "../output/config.json"
  GenPath = "../output/output_"
  FileName = "gen.go"
  PackageName = "gen"
  ClassName = "Gen"
